name: Deploy Backend Azure Function

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'  # This will catch any workflow file changes

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      # Add debug step to see what triggered the workflow
      - name: Debug Trigger
        run: |
          echo "Triggered by changes in:"
          echo "${{ github.event.head_commit.modified }}"
          
      - name: Check out the code
        uses: actions/checkout@v2
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          cd backend/VisitorCounterFunction
          pip install -r requirements.txt
          
      - name: Configure Function App Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          app-settings-json: |
            [
              {
                "name": "COSMOS_DB_ENDPOINT",
                "value": "${{ secrets.COSMOS_DB_ENDPOINT }}"
              },
              {
                "name": "COSMOS_DB_KEY",
                "value": "${{ secrets.COSMOS_DB_KEY }}"
              },
              {
                "name": "FUNCTIONS_WORKER_RUNTIME",
                "value": "python"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "1"
              }
            ]
            
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: ./backend/VisitorCounterFunction
          enable-oryx-build: true
          scm-do-build-during-deployment: true
