name: Blob storage website CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out the code
    - uses: actions/checkout@v3
    
    # Login to Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Set environment variables for Azure Function URL and Key
    - name: Set up environment variables
      run: |
        sed -i 's|__AZURE_FUNCTION_URL__|'"${{ secrets.AZURE_FUNCTION_URL }}"'|g' ./frontend/app.js
        sed -i 's|__AZURE_FUNCTION_KEY__|'"${{ secrets.AZURE_FUNCTION_KEY }}"'|g' ./frontend/app.js

    # Upload to blob storage
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ismailresumestorage --auth-mode key -d '$web' -s ./frontend --overwrite true

    # Azure logout
    - name: Logout from Azure
      run: |
        az logout
      if: always()
