name: Blob storage website CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out the code
    - uses: actions/checkout@v3
    
    # Login to Azure
    - uses: azure/login@v1
      with:
        # Ensure the secrets are set up correctly in GitHub and stored in JSON format with the correct fields
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Upload to blob storage
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ismailresumestorage --auth-mode key -d '$web' -s . --overwrite

    # Azure logout
    - name: Logout from Azure
      run: |
        az logout
      if: always()
